name: Build

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: false
          preCommands: |
            cp wrangler.toml.example wrangler.toml
            sed -ie 's/ACCOUNT_ID/${{ secrets.CF_ACCOUNT_ID }}/g' wrangler.toml
            wrangler build
