name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          preCommands: |
            cp wrangler.toml.example wrangler.toml
            sed -ie 's/ACCOUNT_ID/${{ secrets.CF_ACCOUNT_ID }}/g' wrangler.toml
            wrangler build
